"""add UISetting, WorkGroup

Revision ID: 1301e4c10333
Revises: abbe87c8a2b5
Create Date: 2025-06-06 08:16:13.117354

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1301e4c10333"
down_revision: Union[str, None] = "abbe87c8a2b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
