"""add user migration

Revision ID: 4fd3fdf7cf51
Revises:
Create Date: 2025-06-05 11:11:41.300436

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4fd3fdf7cf51"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
