"""user_cascade_all_add

Revision ID: 847e4749f050
Revises: aa6a4ae9cea0
Create Date: 2025-07-10 14:13:31.769456

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "847e4749f050"
down_revision: Union[str, None] = "aa6a4ae9cea0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
