"""#44-45 migration

Revision ID: 930674e614f9
Revises: dc96723dcab1
Create Date: 2025-06-11 16:22:20.288554

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "930674e614f9"
down_revision: Union[str, None] = "dc96723dcab1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ui_settings", sa.Column("default_company_choice", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "ui_settings", "companies", ["default_company_choice"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ui_settings", type_="foreignkey")
    op.drop_column("ui_settings", "default_company_choice")
    # ### end Alembic commands ###
