"""empty message

Revision ID: a4e29fb05850
Revises: 1301e4c10333
Create Date: 2025-06-06 11:48:06.629612

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a4e29fb05850"
down_revision: Union[str, None] = "1301e4c10333"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
