"""add comany, usercompany migration

Revision ID: abbe87c8a2b5
Revises: 4fd3fdf7cf51
Create Date: 2025-06-05 13:22:09.542586

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "abbe87c8a2b5"
down_revision: Union[str, None] = "4fd3fdf7cf51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
