name: Deploy Backend

on:
  push:
    branches: [ "backend" ]
  pull_request:
    branches: [ "backend" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_COMPOSE_VERSION: 'v2.23.3'
      SSH_PORT: 22
      REMOTE_DIR: ~/QR-sign/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          curl -fsSL https://github.com/docker/compose/releases/download/${{ env.DOCKER_COMPOSE_VERSION }}/docker-compose-linux-x86_64 -o docker-compose
          chmod +x docker-compose
          sudo mv docker-compose /usr/local/bin/

      - name: Build Docker images
        run: docker-compose -f docker-compose.prod.yml build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            cd ${{ env.REMOTE_DIR }}
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d --remove-orphans
            docker system prune -af